In [2]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

2.6.0+cu124
True
Tesla T4


# Creating Tensors

In [3]:
#using empty
a = torch.empty(2,2)
a

tensor([[-1.2163e+04,  4.5440e-41],
        [-1.2163e+04,  4.5440e-41]])

In [4]:
type(a)

torch.Tensor

In [5]:
#using zeros
b = torch.zeros(2,2)
b

tensor([[0., 0.],
        [0., 0.]])

In [6]:
#using ones
c = torch.ones(2,2)
c

tensor([[1., 1.],
        [1., 1.]])

In [7]:
#using rand
d = torch.rand(2,2)
d

tensor([[0.5143, 0.1762],
        [0.1529, 0.5377]])

In [8]:
#using seed
torch.manual_seed(111)
torch.rand(2,2)

tensor([[0.7156, 0.9140],
        [0.2819, 0.2581]])

In [9]:
#using tensor
torch.tensor([[1,2,3], [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
# other ways

#arange
print("using arange ->", torch.arange(0,18,2))

#linspace
print("using linspace ->", torch.linspace(0,18,12))

#eye means Identity
print("using eye ->", torch.eye(5))

#full
print("using full ->", torch.full((3,3), 5))

using arange -> tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])
using linspace -> tensor([ 0.0000,  1.6364,  3.2727,  4.9091,  6.5455,  8.1818,  9.8182, 11.4545,
        13.0909, 14.7273, 16.3636, 18.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


#Tensor Shapes

In [11]:
a.shape

torch.Size([2, 2])

In [12]:
## if we want to create a tensor of same dimension of another tensor
torch.empty_like(c)

tensor([[0.0000e+00, 0.0000e+00],
        [1.8217e-44, 1.8217e-44]])

In [13]:
torch.zeros_like(c)

tensor([[0., 0.],
        [0., 0.]])

In [14]:
torch.ones_like(c)

tensor([[1., 1.],
        [1., 1.]])

In [15]:
torch.rand_like(c)

tensor([[0.6311, 0.6001],
        [0.9312, 0.2153]])

# Tensor Datatypes

In [16]:
#find datatype
c.dtype

torch.float32

In [17]:
#assign datatype
torch.tensor([[1,2,3],[4,5,6]], dtype = torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [18]:
#using to() we can change datatype of an existing tensor
c.to(torch.int32)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

# Mathematical Operations

###Scaler Ops

In [19]:
x = torch.rand(2,2)
x

tensor([[0.6033, 0.7328],
        [0.1857, 0.5101]])

In [20]:
#addition
x = x+2
x
#substraction
x - 2
#multiplication
x * 2
#divsion
x / 2
#power
x ** 2


tensor([[6.7771, 7.4681],
        [4.7774, 6.3004]])

In [21]:
x = torch.ones(2,2)
y = torch.ones(2,2)

In [22]:
x + y
x - y
x * y
x / y
x ** y
x % y

tensor([[0., 0.],
        [0., 0.]])

In [23]:
#abs
z = torch.tensor([1,-3,0,-4])
torch.abs(z)

tensor([1, 3, 0, 4])

In [24]:
#same way we have round, ceil, floor

###Reduction ops

In [25]:
#sum
torch.sum(d)
#sum along col
torch.sum(d, 0)
#sum along row
torch.sum(d, 1)

tensor([0.6905, 0.6906])

In [26]:
#mean
torch.mean(d)
#mean along col
torch.mean(d, 0)
#mean along row
torch.mean(d, 1)

tensor([0.3452, 0.3453])

In [27]:
#same way we have min, max, product, standard dev, variance, argmax, argmin

###Matrix Ops

In [28]:
f = torch.randint(size = (2,2), low = 0, high = 10)
g = torch.randint(size = (2,2), low = 0, high = 10)

In [29]:
torch.matmul(f,g)

tensor([[45, 18],
        [84, 24]])

In [30]:
l = torch.tensor([1,2,3])
r = torch.tensor([1,2,3])
torch.dot(l,r)

tensor(14)

In [31]:
#transpose
torch.transpose(f,0,1)

tensor([[3, 4],
        [3, 8]])

In [32]:
#determinant
torch.det()
#inverse
torch.inverse()

TypeError: det() missing 1 required positional arguments: "input"

###Special Ops

In [33]:
k = torch.randint(size = (2,3), low = 0, high = 50)
k

tensor([[46,  6, 49],
        [26, 16,  1]])

In [34]:
#log
torch.log(k)

tensor([[3.8286, 1.7918, 3.8918],
        [3.2581, 2.7726, 0.0000]])

In [ ]:
#same way we can get exponent, sigmoid, softmax, relu

# Inplace Operations

In [37]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.5982, 0.6111, 0.2544],
        [0.0674, 0.1858, 0.2480]])
tensor([[0.6931, 0.7255, 0.6844],
        [0.2132, 0.7821, 0.0133]])


In [38]:
m.add_(n)

tensor([[1.2913, 1.3366, 0.9389],
        [0.2806, 0.9679, 0.2612]])

In [39]:
#same way we can use relu_

# Copying a Tensor

In [40]:
m = torch.clone(n)

In [41]:
m

tensor([[0.6931, 0.7255, 0.6844],
        [0.2132, 0.7821, 0.0133]])

# Tensor Operations on GPU

In [42]:
device = torch.device('cuda')

In [43]:
torch.rand((2,3), device = device)

tensor([[0.0162, 0.3846, 0.1218],
        [0.4169, 0.4512, 0.0634]], device='cuda:0')

In [44]:
#moving a tensor to gpu

In [46]:
x = m.to(device)
x

tensor([[0.6931, 0.7255, 0.6844],
        [0.2132, 0.7821, 0.0133]], device='cuda:0')

# Reshaping Tensors

In [48]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [52]:
#reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [53]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [55]:
#unsqueeze
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [57]:
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [59]:
#squeeze
c = torch.rand(1,20)
c.squeeze(0).shape

torch.Size([20])

# Numpy and torch

In [60]:
import numpy as np

In [61]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [63]:
b = a.numpy()
b

array([1, 2, 3])

In [64]:
type(a)

torch.Tensor

In [65]:
type(b)

numpy.ndarray

In [66]:
#numpy to tensor
torch.from_numpy(b)

tensor([1, 2, 3])